/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_handball;

import javax.swing.ImageIcon;

/**
 *
 * @author Luka
 */
public class CiklusTrening extends javax.swing.JFrame {

    /**
     * Creates new form CiklusTrening
     */
    public CiklusTrening() {
        initComponents();
         ImageIcon picture = new ImageIcon(getClass().getClassLoader().getResource("Slike/Sijecanj.png"));
            Slika.setIcon(picture);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxMjesec = new javax.swing.JComboBox<>();
        Slika = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CIKLUS TRENINGA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(557, 557, 557)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(599, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ODABERI MJESEC:");

        jComboBoxMjesec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIJECANJ", "VELJACA", "OZUJAK", "TRAVANJ", "SVIBANJ", "LIPANJ", "SRPANJ", "RUJAN", "LISTOPAD", "STUDENI", "PROSINAC" }));
        jComboBoxMjesec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMjesecActionPerformed(evt);
            }
        });

        Slika.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Slika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(jComboBoxMjesec, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMjesec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slika, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMjesecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMjesecActionPerformed
       
        if(jComboBoxMjesec.getSelectedItem()=="SIJECANJ")
        {
            ImageIcon picture = new ImageIcon(getClass().getClassLoader().getResource("Slike/Sijecanj.png"));
            Slika.setIcon(picture);
        }
        
        else if(jComboBoxMjesec.getSelectedItem()=="VELJACA")
        {
            ImageIcon picture = new ImageIcon(getClass().getClassLoader().getResource("Slike/Veljaca.png"));
            Slika.setIcon(picture);
        }
         else if(jComboBoxMjesec.getSelectedItem()=="OZUJAK")
        {
            ImageIcon picture = new ImageIcon(getClass().getClassLoader().getResource("Slike/Ozujak.png"));
            Slika.setIcon(picture);
        }
         else if(jComboBoxMjesec.getSelectedItem()=="TRAVANJ")
        {
            ImageIcon picture = new ImageIcon(getClass().getClassLoader().getResource("Slike/Travanj.png"));
            Slika.setIcon(picture);
        }
         else if(jComboBoxMjesec.getSelectedItem()=="SVIBANJ")
        {
            ImageIcon picture =new ImageIcon(getClass().getClassLoader().getResource("Slike/Svibanj.png"));
            Slika.setIcon(picture);
        }
         else if(jComboBoxMjesec.getSelectedItem()=="LIPANJ")
        {
            ImageIcon picture = new ImageIcon(getClass().getClassLoader().getResource("Slike/Lipanj.png"));
            Slika.setIcon(picture);
        }
         
        
         else if(jComboBoxMjesec.getSelectedItem()=="RUJAN")
        {
            ImageIcon picture =new ImageIcon(getClass().getClassLoader().getResource("Slike/Rujan.png"));
            Slika.setIcon(picture);
        }
         else if(jComboBoxMjesec.getSelectedItem()=="LISTOPAD")
        {
            ImageIcon picture = new ImageIcon(getClass().getClassLoader().getResource("Slike/Listopad.png"));
            Slika.setIcon(picture);
        }
         else if(jComboBoxMjesec.getSelectedItem()=="STUDENI")
        {
            ImageIcon picture = new ImageIcon(getClass().getClassLoader().getResource("Slike/Studeni.png"));
            Slika.setIcon(picture);
        }
         else if(jComboBoxMjesec.getSelectedItem()=="PROSINAC")
        {
            ImageIcon picture = new ImageIcon(getClass().getClassLoader().getResource("Slike/Prosinac.png"));
            Slika.setIcon(picture);
        }
    }//GEN-LAST:event_jComboBoxMjesecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CiklusTrening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CiklusTrening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CiklusTrening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CiklusTrening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CiklusTrening().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Slika;
    private javax.swing.JComboBox<String> jComboBoxMjesec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
