/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_handball;

import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author Luka
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
   
    
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemTablica = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItemTrening = new javax.swing.JMenuItem();
        jMenuItemPTreninga = new javax.swing.JMenuItem();
        jMenuItemPTreninga1 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));

        jMenu1.setText("Odaberi");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItemTablica.setText("Upis igraca");
        jMenuItemTablica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTablicaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTablica);

        jMenuItem6.setText("Tablica");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItemTrening.setText("Ciklus treninga");
        jMenuItemTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTreningActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTrening);

        jMenuItemPTreninga.setText("Prisustvo treninzima");
        jMenuItemPTreninga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPTreningaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPTreninga);

        jMenuItemPTreninga1.setText("Svojstva igraca");
        jMenuItemPTreninga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPTreninga1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPTreninga1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1242, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemTablicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTablicaActionPerformed
     
        //otvaranje forme
        
        UpravljanjeIgraca igrac = new UpravljanjeIgraca();
        igrac.setPreferredSize(new Dimension(1700,950));
        igrac.setVisible(true);
        igrac.pack();
        igrac.setLocationRelativeTo(null);
        igrac.setExtendedState(DISPOSE_ON_CLOSE);
        
                    
        
    }//GEN-LAST:event_jMenuItemTablicaActionPerformed

    private void jMenuItemTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTreningActionPerformed
       
         //otvaranje forme
         
        CiklusTrening ciklus = new CiklusTrening();
        ciklus.setPreferredSize(new Dimension(1650,960));
        ciklus.pack();
        ciklus.setVisible(true);
        ciklus.setLocationRelativeTo(null);
        ciklus.setExtendedState(DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenuItemTreningActionPerformed

    private void jMenuItemPTreningaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPTreningaActionPerformed
       
         //otvaranje forme
        
        TreningForma treninfForma = new TreningForma();
        treninfForma.setPreferredSize(new Dimension(1630,950));
        treninfForma.pack();
        treninfForma.setVisible(true);
        treninfForma.setLocationRelativeTo(null);
        treninfForma.setExtendedState(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemPTreningaActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
         //otvaranje forme
        
        Tablica tablica = new Tablica();
        tablica.setPreferredSize(new Dimension(1610,960));
        tablica.pack();
        tablica.setVisible(true);
        tablica.setLocationRelativeTo(null);
        tablica.setExtendedState(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItemPTreninga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPTreninga1ActionPerformed
       
         //otvaranje forme
        
        IgracSvojstva svojstva = new IgracSvojstva();
        svojstva.setPreferredSize(new Dimension(1615,960));
        svojstva .pack();
        svojstva .setVisible(true);
        svojstva .setLocationRelativeTo(null);
        svojstva .setExtendedState(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemPTreninga1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemPTreninga;
    private javax.swing.JMenuItem jMenuItemPTreninga1;
    private javax.swing.JMenuItem jMenuItemTablica;
    private javax.swing.JMenuItem jMenuItemTrening;
    // End of variables declaration//GEN-END:variables
}
