/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_handball;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luka
 */
public class UpravljanjeIgraca extends javax.swing.JFrame {

    /**
     * Creates new form UpravljanjeIgraca
     */
    
    Igrac igrac = new Igrac();
    public UpravljanjeIgraca() {
        initComponents();
       
        //prikaz tablice  on reload
        
        igrac.prikazIgraca(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new cambodia.raven.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonUpis = new javax.swing.JButton();
        jButtonIzmjena = new javax.swing.JButton();
        jButtonPolja = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldDatum = new javax.swing.JTextField();
        jTextFieldTelefon = new javax.swing.JTextField();
        jTextFieldGolovi = new javax.swing.JTextField();
        jTextFieldVisina = new javax.swing.JTextField();
        jTextFieldTezina = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBoxPozicija = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();

        dateChooser1.setButton(jButton1);
        dateChooser1.setTextRefernce(jTextFieldDatum);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPIS IGRACA");

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Ime:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Prezime:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Telefon:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Datum rodenja:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Pozicija:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Golovi:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Visina:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Tezina:");

        jButtonUpis.setBackground(new java.awt.Color(0, 0, 0));
        jButtonUpis.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonUpis.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpis.setText("UPIS");
        jButtonUpis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpisActionPerformed(evt);
            }
        });

        jButtonIzmjena.setBackground(new java.awt.Color(0, 0, 0));
        jButtonIzmjena.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jButtonIzmjena.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIzmjena.setText("IZMJENI");
        jButtonIzmjena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmjenaActionPerformed(evt);
            }
        });

        jButtonPolja.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPolja.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jButtonPolja.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPolja.setText("OCISTI POLJA");
        jButtonPolja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoljaActionPerformed(evt);
            }
        });

        jTextFieldID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTextFieldIme.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImeActionPerformed(evt);
            }
        });

        jTextFieldPrezime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTextFieldDatum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTextFieldTelefon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTextFieldGolovi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTextFieldVisina.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTextFieldTezina.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Ime", "Prezime", "Telefon", "Datum ", "Pozicija", "Golovi", "Visina", "Tezina"
            }
        )
        //*zabrana editiranja cell-a
        {public boolean isCellEditable(int row,int column){return  false;}}
    );
    jTable1.setGridColor(new java.awt.Color(153, 153, 153));
    jTable1.setRowHeight(30);
    jTable1.setSelectionBackground(new java.awt.Color(102, 102, 102));
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButton1.setBackground(new java.awt.Color(0, 0, 0));
    jButton1.setForeground(new java.awt.Color(255, 255, 255));
    jButton1.setText("...");

    jComboBoxPozicija.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Golman\t", "Lijevo Krilo\t", "Desno Krilo", "Sredmji Vanjski\t", "Lijevi Vanjski", "Desni Vanjski" }));

    jButton2.setBackground(new java.awt.Color(0, 0, 0));
    jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jButton2.setForeground(new java.awt.Color(255, 255, 255));
    jButton2.setText("Osvjezi tablicu");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    jButtonObrisi.setBackground(new java.awt.Color(0, 0, 0));
    jButtonObrisi.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
    jButtonObrisi.setForeground(new java.awt.Color(255, 255, 255));
    jButtonObrisi.setText("OBRISI");
    jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonObrisiActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGap(82, 82, 82))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6)
                            .addGap(12, 12, 12)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldIme)
                                .addComponent(jTextFieldID)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldTezina, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton1))
                                        .addComponent(jComboBoxPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldGolovi, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldVisina, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jButtonObrisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(89, 89, 89))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jButtonPolja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(94, 94, 94))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jButtonUpis, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(jButtonIzmjena, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE))
            .addGap(27, 27, 27))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(34, 34, 34)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGap(34, 34, 34)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jComboBoxPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextFieldGolovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldVisina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGap(37, 37, 37)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(jTextFieldTezina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonUpis, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonIzmjena, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonPolja, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(67, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(588, 588, 588)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 1, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(191, 191, 191))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImeActionPerformed

    private void jButtonUpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpisActionPerformed
                 
        // upis novog igraca u bazu
        
        String ime = jTextFieldIme.getText();
        String prezime = jTextFieldPrezime.getText();
        String telefon = jTextFieldTelefon.getText();
        String datum = jTextFieldDatum.getText();
        String pozicija = jComboBoxPozicija.getSelectedItem().toString();
        String gol = jTextFieldGolovi.getText();
        String visina =jTextFieldVisina.getText();
         String tezina = jTextFieldTezina.getText();     
         if (ime.trim().equals("") || prezime.trim().equals("") || telefon.trim().equals("") || datum.trim().equals("") || gol.trim().equals("") || visina.trim().equals("") || tezina.trim().equals(""))
                 
         {
              JOptionPane.showMessageDialog(rootPane, "Unesite sva polja ", "Greska",JOptionPane.WARNING_MESSAGE);
         }     
                             
         else{                
             
              //poziv na unesti novog igraca iz klase Igrac.Java , DodajIgraca
             
                 if(igrac.DodajIgraca(ime, prezime, telefon, datum, pozicija, gol, visina, tezina))
                         
         {
             JOptionPane.showMessageDialog(rootPane, "Igrac uspjesno unesen ", "Uspjesno upisan",JOptionPane.INFORMATION_MESSAGE);
         } 
         else {
             JOptionPane.showMessageDialog(rootPane, "Igrac  ne uspjesno unesen ", "Molimo vas pokusajte ponovno",JOptionPane.INFORMATION_MESSAGE);
         }
        
    }//GEN-LAST:event_jButtonUpisActionPerformed
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        
        // prikaziva tablice u textfiledovima na klik rowa
        
        //jtable model
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        // uzimanje jednog rowa
        int rowJtable = jTable1.getSelectedRow();
        
        //prikazivanja rowa
        jTextFieldID.setText(model.getValueAt(rowJtable, 0).toString());
        jTextFieldIme.setText(model.getValueAt(rowJtable, 1).toString());
        jTextFieldPrezime.setText(model.getValueAt(rowJtable, 2).toString());
        jTextFieldTelefon.setText(model.getValueAt(rowJtable, 3).toString());
        jTextFieldDatum.setText(model.getValueAt(rowJtable, 4).toString());
        jComboBoxPozicija.setSelectedItem(model.getValueAt(rowJtable, 5).toString());
        jTextFieldGolovi.setText(model.getValueAt(rowJtable, 6).toString());
        jTextFieldVisina.setText(model.getValueAt(rowJtable, 7).toString());
        jTextFieldTezina.setText(model.getValueAt(rowJtable, 8).toString());
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonPoljaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPoljaActionPerformed
       
        //prazna polja na klik butona 'obrisi polje'
        
        jTextFieldID.setText("");
        jTextFieldIme.setText("");
        jTextFieldPrezime.setText("");
        jTextFieldGolovi.setText("");
        jTextFieldVisina.setText("");
        jTextFieldTezina.setText("");
        jTextFieldTelefon.setText("");
        
        
    }//GEN-LAST:event_jButtonPoljaActionPerformed

   
    
    private void jButtonIzmjenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmjenaActionPerformed
       
         //IZMJENA podataka o igracu
         
        int id = 0;
        String ime = jTextFieldIme.getText();
        String prezime = jTextFieldPrezime.getText();
        String telefon = jTextFieldTelefon.getText();
        String datum = jTextFieldDatum.getText();
        String pozicija = jComboBoxPozicija.getSelectedItem().toString();
        String gol = jTextFieldGolovi.getText();
        String visina =jTextFieldVisina.getText();
         String tezina = jTextFieldTezina.getText();   
        
        if (ime.trim().equals("") || prezime.trim().equals("") || telefon.trim().equals("") || datum.trim().equals("") || gol.trim().equals("") || visina.trim().equals("") || tezina.trim().equals(""))
                 
         {
              JOptionPane.showMessageDialog(rootPane, "Unesite sva polja ", "Greska",JOptionPane.WARNING_MESSAGE);
         }     
                             
         else{   
            
            try {
                id = Integer.valueOf(jTextFieldID.getText());
                
                    //poziv izmjene igraca iz klase Igrac.Java , IzmjenaIgraca
                 if(igrac.izmjenaIgraca(id, ime, prezime, telefon, datum, pozicija, gol, visina, tezina))
                         
         {
             JOptionPane.showMessageDialog(rootPane, "Igrac uspjesno izmjenjen ", "Uspjesno izmjenjen",JOptionPane.INFORMATION_MESSAGE);
         } 
         else {
             JOptionPane.showMessageDialog(rootPane, "Igrac  ne uspjesno izmjenjen ", "Molimo vas pokusajte ponovno",JOptionPane.ERROR_MESSAGE);
              }
                }   
               catch (NumberFormatException ex) 
               {
                    JOptionPane.showMessageDialog(rootPane,ex.getMessage() + "Unesite igracev ID", "Igrac ID greska",JOptionPane.ERROR_MESSAGE);        
               } 
    }//GEN-LAST:event_jButtonIzmjenaActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        //brisanje visak polja u tablici
        
          jTable1.setModel(new DefaultTableModel(null, new Object[]{"id","ime","prezime","telefon","datum","pozicija","gol","visina", "tezina"}));
        
        
         //refresh tablice prikaz tablice
        igrac.prikazIgraca(jTable1);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        
        try {
            // moze se korisiti samo ID za brisanje rowa
                int id = Integer.valueOf(jTextFieldID.getText());
                
                 //poziv brisanje igraca iz klase Igrac.Java , obrisiIgraca
                 if(igrac.obrisiIgraca(id))
                         
         {
             JOptionPane.showMessageDialog(rootPane, "Igrac uspjesno obrisan ", "Uspjesno brisanje",JOptionPane.INFORMATION_MESSAGE);
         } 
         else {
             JOptionPane.showMessageDialog(rootPane, "Igrac  ne uspjesno obrisan ", "Molimo vas pokusajte ponovno",JOptionPane.ERROR_MESSAGE);
              }
                }   
               catch (NumberFormatException ex) 
               {
                    JOptionPane.showMessageDialog(rootPane,ex.getMessage() + "Unesite igracev ID", "Igrac ID greska",JOptionPane.ERROR_MESSAGE);        
               } 
        
    }//GEN-LAST:event_jButtonObrisiActionPerformed
           

   

    public static void main(String args[]) {
     
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpravljanjeIgraca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpravljanjeIgraca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpravljanjeIgraca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpravljanjeIgraca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UpravljanjeIgraca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cambodia.raven.DateChooser dateChooser1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonIzmjena;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonPolja;
    private javax.swing.JButton jButtonUpis;
    private javax.swing.JComboBox<String> jComboBoxPozicija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldGolovi;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldTelefon;
    private javax.swing.JTextField jTextFieldTezina;
    private javax.swing.JTextField jTextFieldVisina;
    // End of variables declaration//GEN-END:variables
} 
